# Generated by Django 3.2.20 on 2023-09-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeblog', '0003_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='country',
            field=models.CharField(default='Africa', max_length=150),
        ),
    ]
